name: label_peak_studio

# https://github.com/minio/minio/blob/master/docs/orchestration/docker-compose/docker-compose.yaml
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
  command: server --console-address ":9001" http://minio1/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  minio1:
    <<: *minio-common
    hostname: minio1
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "~/apps/minio/data1-1:/data1"
      - "~/apps/minio/data1-2:/data2"
